### PR TITLE
FIX: NavBar display corrected + types (new test)

### PR DESCRIPTION
**Pull request by frontcodelover**
Fix types on navBar and remove duplicate display (flex & hidden)

### CODE REVIEW

**Comment by AlineAl** [comment]
Thank you for this new PR ! 

After checking, it seems to me that the navigation in mobile format has a bug. When you arrive on the page and arrive directly in mobile format, no problem. 

On the other hand, when you click on a link in the navbar and you arrive in mobile format, the XMark closing icon is displayed first. It should be the opening one that is displayed first.

Capture d’écran 2024-11-09 à 10 47 56

**Comment by frontcodelover** [comment]
Understand, it's not simple. With this PR I tried to fix this :
image

You have hidden and flex at the same time in a same class. 

Do you have any idea ?

**Comment by AlineAl** [comment]
I checked. In the meantime I added a document.addEventListener('astro:page-load', () => {...}} in my main repository that allows to charge page and reset the navbar event.  

So you can take a look in this https://github.com/AlineAl/LaDevdelaToileV3/blob/main/src/components/NavBar.astro to fix this. 

Once you have added the "astro:page-load", make sure the NavBar links on the mobile version are properly centered. As is the case on the project today. And it will be good for me ! 😎

**Comment by frontcodelover** [comment]
Ok I think now it's fixed. Let me know.

**Pull request merged**
